version: 0.2

env:
    variables:
        S3_BUCKET: "site.earninlove.com"
APP_NAME: "earninlove"
BUILD_ENV : "prod"

phases:
    install:
        runtime-versions:
          nodejs : 12
        commands:
        - npm install -g @angular/cli
    build:
        commands:
        - npm install
        - ng build --${BUILD_ENV}

artifacts:
    files:
    - dist/**/*
    discard-paths: no
    name: earninlove
